services:
  json-expert:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: json-expert
    ports:
      - "${PORT:-12355}:80"
    environment:
      - NODE_ENV=production
      - VITE_ALLOWED_DOMAINS=${VITE_ALLOWED_DOMAINS:-jsonexpert.com,localhost}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - json-expert-network

networks:
  json-expert-network:
    driver: bridge
